version: "3"

services: 
    db:
        container_name: "pg_container"
        image: postgres
        ports: 
            - "5432:5432"
        environment: 
            - POSTGRES_DB=tv-tracker
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
        networks: 
            - fullstack
        volumes: 
            - "./bin/db:/var/lib/postgresql/data"

    api: 
        build: .
        container_name: "tracker-rest-api"
        env_file: 
            - .env
        ports: 
            - "8080:8080"
        depends_on:
            - db
        networks: 
            - fullstack
        

networks: 
    fullstack: 
        driver: bridge
